name: Audit dependencies

# Running on the branch main and on all PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_credo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir and OTP
        uses: erlef/setup-beam@v1.15
        id: setup-beam
        with:
          otp-version: '25'
          elixir-version: '1.14.2'

      # Whenever a cache hit occurs for the exact `key` match defined below, this step sets the `cache-hit` outputs to 'true'.
      # With `if: steps.cache.outputs.cache-hit != 'true'`, this can be used in steps to run or ignore them based on the cache hit.
      # A partial key match via `restore-keys` or a cache miss will set `cache-hit` to 'false'.
      - name: Restore dependencies from cache if possible
        uses: actions/cache@v3
        id: cache # To expose the `cache-hit` output through `steps.cache.outputs.cache-hit`
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Check for retired dependencies # https://hexdocs.pm/hex/Mix.Tasks.Hex.Audit.html
        run: mix hex.audit

      - name: Find unused dependencies # https://hexdocs.pm/mix/Mix.Tasks.Deps.Unlock.html
        run: mix deps.unlock --check-unused

      - name: Check for vulnerable dependencies # https://github.com/mirego/mix_audit
        run: mix deps.audit
