name: Lint Elixir code

# Running on the branch main and on all PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_credo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir and OTP
        uses: erlef/setup-beam@v1.15
        with:
          otp-version: '25'
          elixir-version: '1.14.2'

      - name: Install dependencies
        run: mix deps.get

      - name: Lint Elixir code, failing on all issues # Credo's strict analysis: https://hexdocs.pm/credo/basic_usage.html#strict-analysis
        run: mix credo --strict
